### ISSUE TITLE
mysql deletes seem to be broken in .3.0

### ISSUE THREAD

**Issue by mleklund** [theforeman/smart_proxy_dns_powerdns#32] opened 2017-01-13 22:57 UTC
from backend/mysql.rb
```
def delete_record domain_id, name, type
      name = connection.escape(name)
      type = connection.escape(type)
      connection.query("DELETE FROM records WHERE domain_id=#{domain_id} AND name='#{name}' AND type='#{type}'")
      connection.affected_rows >= 1
 end
```

from dns_powerdns_main.rb:
```
def do_remove(name, type)
      zone = get_zone(name)
      if delete_record(zone['id'], name, type)
        raise Proxy::Dns::Error.new("Failed to remove record #{name} #{type}") unless rectify_zone(zone['name'])
      end
      true
 end
```

So whenever 1 or more rows are affected, such as when you delete, it will raise an error.

**Comment by ekohl** [comment] 2017-01-14 10:24
You may notice that there's an ```unless rectify_zone``` there. Perhaps that's failing? In that case I'd also expect insertions and updates to fail but maybe you haven't tested that yet.

I know I've tested this code with integration tests and powerdns 4.0.1 on CentOS 7.3 so I'm quite sure that has to work. What versions are you on?

**Comment by mleklund** [comment] 2017-01-16 14:48
pdns 4.0.1-1pdns.trusty
ubuntu trusty

:powerdns_pdnssec: "false"

We don't use dnssec since this is only internal dns.    Wonder if it is interpreting @pdnssec as a string instead of a bool.  May not really matter since I have switched to the rest backend since it is preferred.

**Comment by ekohl** [comment] 2017-01-16 17:08
It is a string and actually the command that is ran for rectify-zone. This used to be ```pdnssec``` but was renamed to pdnsutil in pdns 4. Since you've used ```false``` it most likely ran ```/bin/false``` which always exits with an error. Leaving it out or using an empty string would have given you the expected behaviour.

Since you switched to the rest backend and I believe this was a misconfiguration I'm going to close this now. Please reopen it if you believe there's still an issue that needs fixing.

**Closed as completed by ekohl** 2017-01-16 17:08 UTC
